### ISSUE TITLE
Calendar popup not loading on IOS/Android devices.

### ISSUE THREAD

**Issue by Sandeepmaale** [PredixDev/px-datetime-picker#11]
Hello, we are using px-datetime-picker in our application (which is responsive) and works fine on desktop. But when the application is accessed from IOS/Android calendar pop-up is not loaded when clicked on calendar icon from px-datetime-field.
Please let us know if there is a fix in progress or there is any workaround with this issue.

Thanks.

**Comment by randyaskin** [comment]
Our general recommendation for mobile devices is to use the native date/time pickers built into the OS. That being said, I have tested it on my iPhone and the px-datetime-picker modal invokes just fine. The px-datetime-entry component uses an on-tap listener (as opposed to on-click) which should be the only thing required to make it mobile-friendly.

Can you provide any additional information?

**Comment by krishnathota** [comment]
The px-datetime-entry component uses input fields for every part of it, but they are readonly. I guess this is the reason the number-pad is not opening when selecting a field in IPad.

**Comment by randyaskin** [comment]
Latest implementation of all datetime components use regular input fields rather than readonly fields.
