### ISSUE TITLE
px-datetime-submitted gets fired multiple times

### ISSUE THREAD

**Issue by HimaniKothari1** [PredixDev/px-datetime-picker#12]
# Submit an Issue

Hi,

I want to track the apply button click event of the date picker and do a save inside the callback. I have added the following listener for the date picker :

 document.addEventListener(
          'px-datetime-submitted', function (evt) {
              if(evt.detail.dateTime) {
                  console.log(evt.detail.dateTime);
              }
          }.bind (this)
      );

Once I hit the apply button on selecting a date, the callback function gets invoked 48 times. (The console statement prints the selected date 48 times). 

Also , I want to add multiple date-pickers on my page, how to identify the the callback based on the date-picker being selected ?

**Comment by randyaskin** [comment]
I am not seeing this behavior anymore in the px-datetime-picker, so either it was anomalous or someone has fixed it in more recent versions. To identify which element fired the event, use `evt.target`.
