### ISSUE TITLE
px-datetime-picker not loading with correct date

### ISSUE THREAD

**Issue by HimaniKothari1** [PredixDev/px-datetime-picker#13]
Hi,

I am trying to use the px-datetime-picker component in my application. I followed the steps as mentioned on the GitHub branch.
But it seems that the component is getting loaded with the current date instead of the date passed in the date-time field while creating the component.
 
I am creating it as below : 
<px-datetime-picker date-format="YYYY/MM/DD" time-format="HH:mm:ss" time-zone="UTC" show-time-zone="abbreviatedText" date-time="2016-02-05T05:30:00.000Z"></px-datetime-picker>
 
The component gets created properly but with current date. I see similar issue on the code pen link available on predixUI/Components.

**Comment by Menkhaus-ge** [comment]
Thank you for bringing this to our attention. 
Pushed a fix to this bug in px-datetime-picker v0.3.8. 

Thanks
