### ISSUE TITLE
date picker not retaining the date section when navigating between months

### ISSUE THREAD

**Issue by vasanthid** [PredixDev/px-datetime-picker#14]
# Submit an Issue
date picker not retaining the date section when navigating between months

## Steps to reproduce the problem:
Open the datepicker by clicking "calendar" icon.  Current date or today's date is selected.
For eg: Feb 9
Navigate to previous or next month. For eg: Navigate to January.
January 9th is selected.

Then, navigate to "February".  
Date selection is lost and "Feb 9" is not highlighted.

## Expected behavior and actual behavior:
Date selection shouldn't be lost.

**Comment by menkhakl** [comment]
Hi @vasanthid, 

The calendar should not retain any date selection when moving between months. 
There is a bug that the selected date changes to the next/previous month when the user first selects on the next/previous buttons.

Thanks

**Comment by Menkhaus-ge** [comment]
Hi @vasanthid,

The calendar should not retain any date selection when moving between months.
There is a bug that the selected date changes to the next/previous month when the user first selects on the next/previous buttons.

Thanks

**Comment by katemenkhaus** [comment]
Fixed in v2.0.8 of px-calendar-picker
