### ISSUE TITLE
Needs a way to show that date has not been set yet

### ISSUE THREAD

**Issue by ichenjulieko** [PredixDev/px-datetime-picker#15]
# Submit an Issue

Hi,

Thanks for helping us improve the Predix UI platform by submitting an issue.

Before you begin, please check the list of existing issues to avoid submitting a duplicate issue.

To help us solve this issue as fast as possible, please fill out the following sections:

## Expected behavior and actual behavior:
Expected: date to be blank when user has not yet picked a date, otherwise it's misleading
Actual: date picker needs a date otherwise an error is thrown

## Environment (_component version number, Browser (including version), operating system, hardware, etc_):
New
Mac El Capitan version 10.11.5
px-date-picker version 0.3.8
## Code examples help us better understand the issue - follow the appropriate codepen for the component by going to https://predix-ui.com, finding the component in question, and clicking on the pencil icon under the demo.
        Once you've created your code example, you can save it under a new url.
        Please note that you should NOT use the same methods for production as the ones used in codepen - these methods are not production ready.

**Comment by Menkhaus-ge** [comment]
Hi @ichenjulieko,

Currently, the datetime components do not support having an empty input value. A moment object is inherent to the architecture of the component.

A datetime component that supports an empty input value is not currently in our backlog.

Thank you, Kate

**Comment by jpradelle** [comment]
I would need it too

**Comment by redninma** [comment]
Team Turbo for Asset also needed the ability for empty values. We have decided not to use this component for now.

**Comment by lokeshkakumanu** [comment]
Team at Renewables Org need this feature too.

**Comment by PaulPerret** [comment]
The Global Timesheet Entry project needs this feature too.

**Comment by randyaskin** [comment]
Latest datetime components support empty state, `required` property, and display an error message if components are required but then submitted without a complete value.
