### ISSUE TITLE
Manually updating date time does not notify

### ISSUE THREAD

**Issue by ugurk** [PredixDev/px-datetime-picker#16]
# Manually updating date time does not notify
## Expected behavior and actual behavior:

Updating date time with picker updates/notifies, but manually editing it (keyboard up,down etc.) won't.

## Steps to reproduce the problem:

```
git clone https://github.com/ugurk/px-datetime-picker
cd px-datetime-picker
npm install
bower install
gulp serve
```

I forked the repo and pushed a commit that shows date time variable in a span.

## Environment (_component version number, Browser (including version), operating system, hardware, etc_):

Chrome v56 on Windows 7

## Code examples

https://github.com/ugurk/px-datetime-picker

BTW: codepen link on demo page is dead.

**Comment by nonmetalhail** [comment]
Someone submitted #17 to try and fix your problem. Please pull the latest and see if your problem is fixed.

**Comment by ugurk** [comment]
@nonmetalhail now it works as expected
