### ISSUE TITLE
issue with px-datetime-picker

### ISSUE THREAD

**Issue by 502383987** [PredixDev/px-datetime-picker#18]
i am using px-datetime-picker component 
<px-datetime-picker id="dateOfInspectionId"   hide-time="true" date-format="YYYY/MM"  show-time-zone="none" date-time="2017-04-12T10:26:40.000Z"></px-datetime-picker> 

//setting a date to the datetime picker component using dateTime attribute 
var displayDate= '2017-03-01'; 
document.getElementById('dateOfInspectionId').dateTime = displayDate; 
Now after setting the date and when i read the same value again 
console.log(document.getElementById('dateOfInspectionId').dateTime); 
2017-02-01 
I am seeing a one month difference in the output. 
could you please tell me the way to fix this

**Comment by randyaskin** [comment]
As I said on the forums, I'm not able to replicate this. Per the issue template (which you've ignored), can you provide us a CodePen or JSFiddle of this happening in the standalone component?

**Comment by randyaskin** [comment]
By any chance are you using the date-format property of `YYYY-DD-MM` and it is appearing off by one *day* instead of one *month*? We have seen *that* issue before, the root cause being the difference between UTC and whatever time zone you're located in.

**Comment by 502383987** [comment]
we are getting a difference of one day to the date that we have set . if i set the date as 14-02-2017 , i am getting 13-02-2017
is this something that can be fixed

**Comment by randyaskin** [comment]
@Menkhaus-ge - can you please explain the UTC / timezone discrepancy and how to get around it?

**Comment by nonmetalhail** [comment]
Per the docs, your datetime should be formatted as an ISO 8601 string. Your dateTime is not a properly formatted ISO 8601 string and is probably getting interpreted incorrectly as a result. This value is probably also different in different browsers too as each will interpret it differently. 

To solve this, 1) provide a full ISO 8601 string: `"2013-01-07T22:44:30.652Z"`, 2) if you want a specific timezone, provide a timeZone. See: [https://www.predix-ui.com/#/components/px-datetime-picker/](https://www.predix-ui.com/#/components/px-datetime-picker/)
