### ISSUE TITLE
Today option and mouse click on dates not working

### ISSUE THREAD

**Issue by satishpoul** [PredixDev/px-datetime-picker#20]
# Today option and mouse click on dates not working

Hi Team,

I am providing steps to produce an error which i am facing :

## Steps to produce : 
1) Toggle Block Future Dates to true. (All future dates get disabled for mouse) (Can try with blocking past dates as well.)
2) By keyboard select any future date (although it is blocked keyboard can navigate to the any dates).
3) Open Calendar and press Today.
4) Mouse Click on any allowed date.

## Current Behaviour:
first time, On pressing today, calendar navigates to (_today's date - 1_)
After this, if you click Today or Click on any allowed dates on calendar date selection wont changed.

## Expected behavior:
On pressing Today, calendar should navigate to exact today's date, Selected date should change.
Mouse click should change the selected date value.

## Refer screenshot below
![datetimeissue](https://cloud.githubusercontent.com/assets/3095213/25891296/2c1d1e46-358e-11e7-8ac7-c83033efb9f2.jpg)

**Comment by katemenkhaus** [comment]
Cannot recreate in latest version `v2.0.4`
Reopen if you still have this issue.
