### ISSUE TITLE
Allows to select the back date as year “0000”

### ISSUE THREAD

**Issue by pruthvi-p** [PredixDev/px-datetime-picker#21]
# Submit an Issue or feature enhancement

Hi,

Using this control we want to restrict the user from selecting the past date less than the given date. 
For example: I want to restrict the user from selecting the date before year 1970 but currently it is allowing user to select even "0000"

It might be a feature enhancement.

**Comment by randyaskin** [comment]
Support for `min` and `max` were added back in August, apologies for not updating this issue.
