### ISSUE TITLE
No easy option to show calendar above picker

### ISSUE THREAD

**Issue by lhoggatt** [PredixDev/px-datetime-picker#22]
# Submit an Issue

Hi,

Thanks for helping us improve the Predix UI platform by submitting an issue.

Before you begin, please check the list of existing issues to avoid submitting a duplicate issue.

To help us solve this issue as fast as possible, please fill out the following sections:

## Expected behavior and actual behavior:

When clicking on the calendar symbol to bring up the calendar and when my picker is near the bottom of the web page, the calendar does not pop up above the picker. Instead, it goes below the picker and forces the user to scroll. 

## Steps to reproduce the problem:

[see previous]

## Environment (_component version number, Browser (including version), operating system, hardware, etc_):

Using v0.4.0
Chrome 58
Windows 7
Dell Laptop (core i5, SSD, etc)

## Screenshots (_optional, but very helpful_):

As you can see here, the calendar is showing up below the picker instead of above the picker:
![image](https://user-images.githubusercontent.com/29959167/27929094-3860e3ae-6257-11e7-9744-6014492251db.png)

## Code examples help us better understand the issue - follow the appropriate codepen for the component by going to https://predix-ui.com, finding the component in question, and clicking on the pencil icon under the demo.
        Once you've created your code example, you can save it under a new url.
        Please note that you should NOT use the same methods for production as the ones used in codepen - these methods are not production ready.

Codepen not working so no example given (here is the predix link):
https://www.predix-ui.com/#/components/px-datetime-picker/

**Comment by randyaskin** [comment]
With migration to iron-dropdown 3 months ago, dynamic alignment of the datetime picker is now automatic.
