### ISSUE TITLE
Calendar Pop-Up positioning non-responsive

### ISSUE THREAD

**Issue by jenarhanes** [PredixDev/px-datetime-picker#25]
# Submit an Issue

Hi,

Thanks for helping us improve the Predix UI platform by submitting an issue.

Before you begin, please check the list of existing issues to avoid submitting a duplicate issue.

To help us solve this issue as fast as possible, please fill out the following sections:

## Expected behavior and actual behavior:
expected: calendar pop-up should position/appear at the center of the screen regardless of my current view of the page (i.e. if I have scrolled to a the bottom of the page, I should not have to scroll up to the top of the page to see the pop-up).
actual: calendar pop-up only positions/appears at the top of the html page such that, if I have scrolled down to get to it, I have to scroll up to select dates

## Steps to reproduce the problem:
-Make a long scroll
-Put the date picker at the bottom
-Attempt to select dates

## Environment (_component version number, Browser (including version), operating system, hardware, etc_):
{
  "name": "SampleWidgetRepository",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "start": "node app.js",
    "postinstall": "npm install -g bower ",
    "_postinstall": "cp ./git_hooks/pre-push ./.git/hooks/pre-push && chmod +x .git/hooks/pre-push || echo skipping post install"
  },
  "dependencies": {
    "body-parser": "~1.13.2",
    "chalk": "^1.1.3",
    "cookie-parser": "~1.3.5",
    "debug": "~2.2.0",
    "express": "~4.13.1",
    "grunt": "~v0.4.5",
    "grunt-vulcanize": "^1.0.0",
    "gulp": "^3.9.1",
    "gulp-file": "^0.3.0",
    "gulp-inject": "^4.2.0",
    "gulp-inject-string": "^1.1.0",
    "gulp-rename": "^1.2.2",
    "gulp-template": "^4.0.0",
    "inquirer": "^3.1.1",
    "jade": "~1.11.0",
    "morgan": "~1.6.1",
    "run-sequence": "^2.0.0",
    "serve-favicon": "~2.3.0",
    "web-component-tester": "^6.0.0",
    "yosay": "^2.0.0"
  }
}
API Training Shop Blog About
© 2017 GitHub, Inc. Help Support

## Screenshots (_optional, but very helpful_):
[doesn't really help here - honestly - I made two and they really don't do it justice]

## Code examples help us better understand the issue - follow the appropriate codepen for the component by going to https://predix-ui.com, finding the component in question, and clicking on the pencil icon under the demo.
        Once you've created your code example, you can save it under a new url.
        Please note that you should NOT use the same methods for production as the ones used in codepen - these methods are not production ready.

**Comment by randyaskin** [comment]
We are already working on two things that may help - an implementation of the datetime components that uses iron-dropdown for intelligent positioning, and a mobile-friendly version of the datetime components. Stay tuned!

**Comment by randyaskin** [comment]
Iron-dropdown implementation has been released, popup will align dynamically based on space available.
