### ISSUE TITLE
Not able to integrate datetime picker into GEDA code due to js issues

### ISSUE THREAD

**Issue by jitadash** [PredixDev/px-datetime-picker#29]
# Submit an Issue

Hi,

Thanks for helping us improve the Predix UI platform by submitting an issue.

Before you begin, please check the list of existing issues to avoid submitting a duplicate issue.

To help us solve this issue as fast as possible, please fill out the following sections:

## Code examples help us better understand the issue - follow the appropriate codepen for the component by going to https://predix-ui.com, finding the component in question, and clicking on the pencil icon under the demo.
        Once you've created your code example, you can save it under a new url.
        Please note that you should NOT use the same methods for production as the ones used in codepen - these methods are not production ready.

**Comment by jitadash** [comment]
VM1397 bundle.v1.0.0.js:10709 Uncaught ReferenceError: pxDatetimeSharedBehavior is not defined
    at Object.b (VM1397 bundle.v1.0.0.js:10709)
    at __webpack_require__ (VM1397 bundle.v1.0.0.js:362)
    at Object.<anonymous> (VM1397 bundle.v1.0.0.js:35993)
    at __webpack_require__ (VM1397 bundle.v1.0.0.js:362)
    at Object.<anonymous> (VM1397 bundle.v1.0.0.js:27108)
    at __webpack_require__ (VM1397 bundle.v1.0.0.js:362)
    at VM1397 bundle.v1.0.0.js:405
    at VM1397 bundle.v1.0.0.js:408
b @ VM1397 bundle.v1.0.0.js:10709
__webpack_require__ @ VM1397 bundle.v1.0.0.js:362
(anonymous) @ VM1397 bundle.v1.0.0.js:35993
__webpack_require__ @ VM1397 bundle.v1.0.0.js:362
(anonymous) @ VM1397 bundle.v1.0.0.js:27108
__webpack_require__ @ VM1397 bundle.v1.0.0.js:362
(anonymous) @ VM1397 bundle.v1.0.0.js:405
(anonymous) @ VM1397 bundle.v1.0.0.js:408
14:18:18.961 VM1397 bundle.v1.0.0.js:30797 XHR finished loading: GET "http://localhost:8080/sockjs-node/info?t=1515709098609".
AbstractXHRObject._start @ VM1397 bundle.v1.0.0.js:30797
(anonymous) @ VM1397 bundle.v1.0.0.js:30686
setTimeout (async)
AbstractXHRObject @ VM1397 bundle.v1.0.0.js:30685
XHRCorsObject @ VM1397 bundle.v1.0.0.js:32063
InfoAjax @ VM1397 bundle.v1.0.0.js:29552
InfoReceiver._getReceiver @ VM1397 bundle.v1.0.0.js:29735
InfoReceiver.doXhr @ VM1397 bundle.v1.0.0.js:29752
(anonymous) @ VM1397 bundle.v1.0.0.js:29721
setTimeout (async)
InfoReceiver @ VM1397 bundle.v1.0.0.js:29720
SockJS @ VM1397 bundle.v1.0.0.js:29926
initSocket @ VM1397 bundle.v1.0.0.js:29157
(anonymous) @ VM1397 bundle.v1.0.0.js:27315
(anonymous) @ VM1397 bundle.v1.0.0.js:27359
__webpack_require__ @ VM1397 bundle.v1.0.0.js:362
(anonymous) @ VM1397 bundle.v1.0.0.js:27107
__webpack_require__ @ VM1397 bundle.v1.0.0.js:362
(anonymous) @ VM1397 bundle.v1.0.0.js:405
(anonymous) @ VM1397 bundle.v1.0.0.js:408
14:18:32.527 bundle.v1.0.0.js:27195 [WDS] App updated. Recompiling...
14:18:32.759 bundle.v1.0.0.js:27195 [WDS] App updated. Recompiling...
14:18:34.628 bundle.v1.0.0.js:27354 [WDS] App updated. Reloading...
14:18:34.736 Navigated to http://localhost:3000/digital-asset/
14:18:35.038 px-datetime-behavior.html:52 Uncaught ReferenceError: pxDatetimeSharedBehavior is not defined
    at Object.b (px-datetime-behavior.html:52)
    at __webpack_require__ (bootstrap d69d6d8a14a18b0ca168:361)
    at Object.<anonymous> (events.js:302)
    at __webpack_require__ (bootstrap d69d6d8a14a18b0ca168:361)
    at Object.<anonymous> (bundle.v1.0.0.js:27107)
    at __webpack_require__ (bootstrap d69d6d8a14a18b0ca168:361)
    at bootstrap d69d6d8a14a18b0ca168:404
    at bootstrap d69d6d8a14a18b0ca168:404

**Comment by benoitjchevalier** [comment]
Thank you for following the template, that really helps us helping you.

I have no idea what GEDA is.

`14:18:35.038 px-datetime-behavior.html:52 Uncaught ReferenceError: pxDatetimeSharedBehavior is not defined` seems to indicate that you are missing one of the behaviors, so maybe one of the files hasn't been included.
