### ISSUE TITLE
How to focus px-datetime-picker programmatically?

### ISSUE THREAD

**Issue by limonte** [PredixDev/px-datetime-picker#30]
```js
document.querySelector('px-datetime-picker').focus()
```

doesn't seem to work.

**Comment by katemenkhaus** [comment]
Why are you trying to focus on the whole picker, as opposed to the calendar icon or the first cell in the field?

**Comment by limonte** [comment]
> Why are you trying to focus on the whole picker, as opposed to the calendar icon or the first cell in the field?

It's related to keyboard a11y of px-data-grid. When user hits `Enter`, `px-data-grid-cell-content-wrapper` triggers the `focus` on the input inside it.

Right now when user hits `Enter` on a cell with `px-datetime-picker` inside it, nothing happens because `px-datetime-picker` doesn't react anyhow on `.focus()` event:

![peek 2018-02-27 13-18](https://user-images.githubusercontent.com/6059356/36725965-bc73ff96-1bc0-11e8-9b7f-32eb51b0bfc0.gif)
