### ISSUE TITLE
"message": "No tag found that was able to satisfy ~0.4.13",

### ISSUE THREAD

**Issue by NareshChennuri** [PredixDev/px-datetime-picker#4]
Unable to install the package, I am getting the below error;

  "id": "ENORESTARGET",
  "level": "error",
  "message": "No tag found that was able to satisfy ~0.4.13",
  "stacktrace": "Error: No tag found that was able to satisfy ~0.4.13\n    at createError (C:\\Users\\NC469762\\AppData\\Roaming\\npm\\node_modules\\bower\\lib\\util\\createError.js:4:15)\n    at C:\\Users\\NC469762\\AppData\\Roaming\\npm\\node_modules\\bower\\lib\\core\\resolvers\\GitResolver.js:145:23\n    at C:\\Users\\NC469762\\AppData\\Roaming\\npm\\node_modules\\bower\\lib\\node_modules\\q\\q.js:1229:26\n    at _fulfilled (C:\\Users\\NC469762\\AppData\\Roaming\\npm\\node_modules\\bower\\lib\\node_modules\\q\\q.js:834:54)\n    at self.promiseDispatch.done (C:\\Users\\NC469762\\AppData\\Roaming\\npm\\node_modules\\bower\\lib\\node_modules\\q\\q.js:863:30)\n    at Promise.promise.promiseDispatch (C:\\Users\\NC469762\\AppData\\Roaming\\npm\\node_modules\\bower\\lib\\node_modules\\q\\q.js:796:13)\n    at C:\\Users\\NC469762\\AppData\\Roaming\\npm\\node_modules\\bower\\lib\\node_modules\\q\\q.js:556:49\n    at runSingle (C:\\Users\\NC469762\\AppData\\Roaming\\npm\\node_modules\\bower\\lib\\node_modules\\q\\q.js:137:13)\n    at flush (C:\\Users\\NC469762\\AppData\\Roaming\\npm\\node_modules\\bower\\lib\\node_modules\\q\\q.js:125:13)\n    at process._tickCallback (node.js:355:11)"
}]

**Comment by mdwragg** [comment]
Ooops, I'll take a look at that right now.

**Comment by mdwragg** [comment]
Fixed by 31b7374ea3a289eeeccaa193eb6d7d3a5f2af9bc
