### ISSUE TITLE
px-datepicker issue: px-datetime-submitted event gets fired without 'Apply' being called for. It also fires without any date time modification being selected.

### ISSUE THREAD

**Issue by jyotsnaravikumar** [PredixDev/px-datetime-picker#7]
Hello,

Currently we see problem with px-datepicker.
 
PX-datepicker - Used the documentation mentioned here - https://predixdev.github.io/px-datetime-picker/px-datetime-picker/
   The above documentation mentions:
px-datetime-submitted event. This event is fired differently depending on config:
&#8226                       If the px-datetim component has an apply button then it is fired when the user clicks the apply button (or press enter) AND the date/time is valid
&#8226                       If the px-datetim component does not have an apply button then it is fired every time a change is made to the date/time AND the date/time is valid
 
 
However the px-datetime-submitted event gets fired without 'Apply' being called for. It also fires without any date time modification being selected.

The unit test sample just shows the event getting fired, however our requirement is modify the date and apply, so expected behavior as per documentation is px-datetime-submitted event should be fired on apply button.

Also would be helpful to have more unit tests showing all scenarios of datetime picker like displaying the date, modifying the date etc.

Thanks,
Jyotsna

**Comment by benoitjchevalier** [comment]
Hello,

Could you please clarify the issue? The demo seem to behave as expected, i.e the event is fired when clicking 'apply' if the panel has an apply button, and always when choosing a date in the panel if it has no apply button.

When choosing a date outside of the panel, i.e by typing the date in the textbox, the event is always fired as there is no apply button related to the textbox. Is this the issue?

Also I'm not sure what you mean about the unit tests, are you talking about our wct unit tests or the demo page?

**Comment by jyotsnaravikumar** [comment]
Hello,

Here is how I am using the date picker component ..

In my html:
<px-datetime-picker 
                id="dateTime"
                date-time="{{caseClosedOnDate}}"
                date-format="MM/DD/YY"
                time-format="hh:mm A"
                show-buttons="true"
                block-future-dates="true"
                hide-time="true">
        </px-datetime-picker>

In the controller I am handling the event to update the date as:
   document.addEventListener('px-datetime-submitted', function(evt) {
            //   this.log.debug(evt);
            caseRepository.update(caseUuid, {caseClosedOnDate: evt.detail.dateTime});
        });

However the px-datetime-submitted is fired even without datepicker clicked or apply called,

**Comment by benoitjchevalier** [comment]
The event is most likely fired because you're setting a new date through the binding and the date is being validated and accepted.

If all you are interested in is when the user clicks apply you might want to listen to `px-datetime-button-clicked` and make sure that evt.detail.action is true (true when clicking apply, false when clicking cancel)

**Comment by jyotsnaravikumar** [comment]
Is there any documentation available to handle this px-datetime-button-clicked event? Where do I handle the apply and cancel scenario? 

Somthing like this? So where do I set the evt.detail.action is true (true when clicking apply, false when clicking cancel)
   document.addEventListener('px-datetime-button-clicked', function(evt) {
            caseRepository.update(caseUuid, {caseClosedOnDate: evt.detail.dateTime});
        });

**Comment by benoitjchevalier** [comment]
unfortunately those events haven't been documented yet. The only info available from those is whether apply or cancel has been clicked. The other issue is that button-clicked fires before the date is validated, so you'll have to listen to datetime-submitted within the button-clicked listener. Somehting along the lines of (you might have to adjust syntax):

```
yourRangePicker.addEventListener('px-datetime-button-clicked', function(evt) {
     if(evt.detail.action) {
        //APPLY HAS BEEN CLICKED. 
        //unfortunately the date/time hasn't been processed yet. 

        //listener for the submit event
        var submitListener =  function(submitEvt) {
             caseRepository.update(caseUuid, {caseClosedOnDate: submitEvt.detail.dateTime});
        }
 
        //listen to the submitted event
        yourRangePicker.addEventListener('px-datetime-submitted', submitListener);

       //make sure we remove the listener, whether the change has been processed or not
       setTimeout(function() {
            yourRangePicker.removeEventListener('px-datetime-submitted', submitListener);
       }, 50);//might have to adjust the timeout
        
     } else {
        //CANCEL HAS BEEN CLICKED
      }
});
```

hope that helps. The other solution would be keeping your previous listener on px-datetime-submitted and using a flag to know whetehr the changes comes from your app or not, preventing the call to caseRepository.update(caseUuid, {caseClosedOnDate: evt.detail.dateTime}); if it does come from your app rather than the user.

**Comment by benoitjchevalier** [comment]
I'm closing this for now, please reopen if you're still experiencing issues
