### ISSUE TITLE
Date object is not updating when future date is select with calendar picker and blockPastDate is enabled

### ISSUE THREAD

**Issue by gigmania** [PredixDev/px-datetime-picker#8]
Expected behavior
The date object should update when a future date is selected with the calendar picker.

Current behavior 
The date object does not update when a future date is selected with the calendar picker.

Steps to reproduce
1) visit https://predixdev.github.io/predix-ui/?show=px-datetime-picker&type=component
2) toggle blockPastDates property to true
3) use the calendar picker to select a future date

Potential fixes
1) This fix isolates any undiscovered negative impact to the behavior of the datetime-picker https://github.com/gigmania/px-datetime-picker/tree/blockPastDateBehaviorFix
2) This fix has high potential of breaking other datetime components and is not recommended. https://github.com/gigmania/px-datetime-common/tree/initDateIsPast

**Comment by Menkhaus-ge** [comment]
We have found that there is a timing issue happening with the validation. 
Right now there doesn't seem to be an easy solution. While we work to solve this, you can in the mean time set show-buttons to true to avoid this issue.

**Comment by gigmania** [comment]
Thanks for the update Kate. The Cancel and Apply buttons are not aligned with the project UX requirements. While we wait for the bug to get fixed we are going to use a customized fork of px-datatime-picker.

**Comment by Menkhaus-ge** [comment]
This issue has been fix with v0.2.11. 
Thank you for helping us make Predix UI better.
